name: Release Zip

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Configure Git
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: 'Make Zip'
        run: |
          mkdir dnd4e
          cp -r folder/ folder2/ dnd4e
        # zip -r dnd4e.zip dnd4e
      - name: 'Upload Zip'
        uses: actions/upload-artifact@v2
        with:
          name: system-zip
          path: ./dnd4e
          retention-days: 1
