name: Release Zip

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update manifest.json download path
        uses: jossef/action-set-json-field@v1
        with:
          file: manifest.json
          field: download
          value: "https://github.com/mdekrey/actions-testing/releases/download/${{github.ref_name}}/dnd4e.zip"
      - id: get-version
        run: |
          version=$(echo ${{github.ref_name}} | sed s/v//)
          echo "::set-output name=version::$version"

      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v1
        with:
          file: manifest.json
          field: version
          value: "${{steps.get-version.outputs.version}}"

      - name: 'Make Zip'
        run: |
          mkdir output
          mkdir output/dnd4e
          cp -r folder/ folder2/ output/dnd4e
          cd output
          zip -r ../dnd4e.zip dnd4e

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dnd4e.zip,manifest.json"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Change and update'
        run: |
          mv manifest.json ../
          git reset --hard
          rm -rf output/
          git checkout gh-pages
          cp ../manifest.json dnd4e.json
          git add dnd4e.json
          git commit -m "Release ${{github.ref_name}}"
          git push origin HEAD:gh-pages
